'use client'
import { useEffect, useMemo, useState } from 'react'
import { Search, Activity, Users, Eye, Heart, ThumbsUp, CalendarDays, RefreshCw, ExternalLink, Database, TrendingUp, Server, Copy, Check, BarChart3, Clock3, Gauge, ShieldCheck } from 'lucide-react'
import { AreaChart, Area, LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, BarChart, Bar } from 'recharts'

type Data = any
const fmt = (n:any) => n == null || Number.isNaN(Number(n)) ? '—' : Intl.NumberFormat('fr-FR',{notation:Number(n)>999999?'compact':'standard',maximumFractionDigits:1}).format(Number(n))
const pct = (n:any,d=1) => n == null || Number.isNaN(Number(n)) ? '—' : `${Number(n).toFixed(d)}%`
const date = (s:any) => s ? new Date(s).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'}) : '—'
const days = (n:any) => n == null ? '—' : n < 365 ? `${Math.round(n)} j` : `${(n/365.25).toFixed(1)} ans`

function Metric({icon:Icon,label,value,sub,good}:{icon:any,label:string,value:any,sub?:string,good?:boolean}){return <div className="metric"><div className="metricIcon"><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong>{sub&&<small className={good?'up':''}>{sub}</small>}</div></div>}
function InfoCard({title,value,text,children}:{title:string,value:any,text:string,children?:React.ReactNode}){return <div className="infoCard"><span>{title}</span><strong>{value}</strong><p>{text}</p>{children}</div>}
function EmptyChart({text}:{text:string}){return <div className="chartEmpty">{text}</div>}

export default function Home(){
 const [query,setQuery]=useState(''); const [data,setData]=useState<Data>(); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [tab,setTab]=useState('overview'); const [history,setHistory]=useState<any[]>([]); const [copied,setCopied]=useState(false)
 const load=async(q=query)=>{if(!q)return;setLoading(true);setError('');try{const r=await fetch('/api/roblox?q='+encodeURIComponent(q));const j=await r.json();if(!r.ok)throw Error(j.error);setData(j);setTab('overview')}catch(e:any){setError(e.message||'Impossible de récupérer les données')}finally{setLoading(false)}}
 useEffect(()=>{try{const raw=localStorage.getItem('rbx-history-v2');if(raw)setHistory(JSON.parse(raw))}catch{}},[])
 useEffect(()=>{if(!data)return;const point={time:Date.now(),label:new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),playing:data.universe.playing,visits:data.universe.visits,favorites:data.favorites,id:data.universe.id};const next=[...history.filter(x=>x.id!==data.universe.id),point].slice(-240);setHistory(next);localStorage.setItem('rbx-history-v2',JSON.stringify(next))},[data])
 const gameHistory=useMemo(()=>history.filter(x=>data&&x.id===data.universe.id).sort((a,b)=>a.time-b.time),[history,data])
 const creatorSeries=useMemo(()=>data?.history?.privateAnalytics?.metrics?.DailyActiveUsers||[],[data])
 const revenueSeries=useMemo(()=>data?.history?.privateAnalytics?.metrics?.DailyRevenue||[],[data])
 const copy=()=>{navigator.clipboard.writeText(String(data?.universe?.id));setCopied(true);setTimeout(()=>setCopied(false),1200)}
 const tabs=[['overview','Vue générale'],['history','Historique'],['engagement','Engagement'],['growth','Croissance'],['technical','Technique'],['raw','Données brutes']]
 return <main>
  <header className="top"><div className="brand"><div className="logo">R</div><div><b>RBX<span> Analytics</span></b><small>ROBLOX GAME INTELLIGENCE · V2</small></div></div><div className="status"><i/> API CONNECTED</div></header>
  <section className="hero"><div className="eyebrow">ROBLOX DATA EXPLORER · V2</div><h1>Analyse n'importe quel<br/><em>jeu Roblox.</em></h1><p>Un vrai tableau de bord d'analyse : activité, croissance, engagement, votes, âge du jeu, ratios, historique disponible et données Creator Analytics quand tu as les permissions.</p>
   <div className="search"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Nom du jeu, URL Roblox ou Universe ID…"/><button onClick={()=>load()} disabled={loading}>{loading?<RefreshCw className="spin" size={18}/>:<Search size={18}/>} Analyser</button></div>
   {error&&<div className="error">{error}</div>}
   <div className="examples"><span>Tester :</span>{['Grow a Garden','Steal a Brainrot','Brookhaven RP','Blox Fruits'].map(x=><button key={x} onClick={()=>{setQuery(x);load(x)}}>{x}</button>)}</div>
  </section>
  {!data?<section className="empty"><Database size={34}/><h2>Ton laboratoire Roblox</h2><p>Recherche un jeu pour ouvrir son profil analytique complet.</p><div className="features"><div><Activity/><b>Live metrics</b><small>CCU, visites, favoris, votes, serveurs</small></div><div><TrendingUp/><b>Growth intelligence</b><small>Ratios, rythme moyen et signaux de croissance</small></div><div><BarChart3/><b>Historical data</b><small>Snapshots locaux + Creator Analytics si disponible</small></div></div></section>:
  <section className="dashboard">
   <div className="gameHead"><img src={data.icon||data.media?.data?.[0]?.imageUrl||''} onError={e=>(e.currentTarget.style.display='none')} /><div><div className="live"><i/> LIVE SNAPSHOT · {new Date(data.fetchedAt).toLocaleTimeString('fr-FR')}</div><h2>{data.universe.name}</h2><p>{data.universe.description||'Aucune description disponible.'}</p><div className="chips"><span>{data.universe.genre||'Genre inconnu'}</span><span>Universe {data.universe.id}</span><span>{days(data.derived?.ageDays)} d'ancienneté</span></div></div><a href={`https://www.roblox.com/games/${data.universe.rootPlaceId}`} target="_blank" rel="noreferrer"><ExternalLink size={17}/> Roblox</a></div>
   <nav className="tabs">{tabs.map(([k,v])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{v}</button>)}<button className="refresh" onClick={()=>load()}><RefreshCw size={15}/></button></nav>
   {tab==='overview'&&<>
    <div className="metrics"><Metric icon={Users} label="JOUEURS EN LIGNE" value={fmt(data.universe.playing)} sub="CCU maintenant" good/><Metric icon={Eye} label="VISITES TOTALES" value={fmt(data.universe.visits)} sub={`${fmt(data.derived?.visitsPerDay)} / jour moyen`}/><Metric icon={Heart} label="FAVORIS" value={fmt(data.favorites)} sub={`${pct(data.derived?.favoriteRate,3)} des visites`}/><Metric icon={ThumbsUp} label="LIKE RATE" value={pct(data.derived?.likeRate,1)} sub={`${fmt(data.votes?.upVotes)} likes`}/><Metric icon={Server} label="SERVEURS ESTIMÉS" value={fmt(data.derived?.estimatedServers)} sub={`${fmt(data.universe.maxPlayers)} max / serveur`}/><Metric icon={CalendarDays} label="ÂGE DU JEU" value={days(data.derived?.ageDays)} sub={`créé ${date(data.universe.created)}`}/></div>
    <div className="grid2"><div className="panel"><div className="panelTitle"><div><span>CONCURRENT PLAYERS</span><h3>Activité observée</h3></div><span className="pill">{gameHistory.length} snapshots</span></div><div className="bigNumber">{fmt(data.universe.playing)} <small>players</small></div>{gameHistory.length>1?<ResponsiveContainer width="100%" height={130}><AreaChart data={gameHistory}><Area type="monotone" dataKey="playing" strokeWidth={2} fillOpacity={.12}/><Tooltip/></AreaChart></ResponsiveContainer>:<EmptyChart text="Actualise plusieurs fois pour créer ton historique local."/>}</div>
      <div className="panel"><div className="panelTitle"><div><span>HEALTH SIGNALS</span><h3>Scorecard analytique</h3></div></div><div className="bars"><div><label>Like rate</label><div className="bar"><i style={{width:`${Math.min(100,data.derived?.likeRate||0)}%`}}/></div><b>{pct(data.derived?.likeRate)}</b></div><div><label>Serveur rempli</label><div className="bar"><i style={{width:`${Math.min(100,data.derived?.serverFill||0)}%`}}/></div><b>{pct(data.derived?.serverFill)}</b></div><div><label>Favorite conversion</label><div className="bar"><i style={{width:`${Math.min(100,(data.derived?.favoriteRate||0)*20)}%`}}/></div><b>{pct(data.derived?.favoriteRate,3)}</b></div></div></div></div>
   </>}
   {tab==='history'&&<div className="sectionGrid"><InfoCard title="COUVERTURE" value={data.history?.privateAnalytics?.enabled?'Creator Analytics':'Snapshots locaux'} text={data.history?.privateAnalytics?.enabled?'Données propriétaires Roblox détectées pour ce jeu.':'Les API publiques Roblox ne donnent pas un historique CCU rétroactif universel.'}/><InfoCard title="DEPUIS" value={date(data.history?.privateAnalytics?.startTime||data.universe.created)} text="Point de départ réellement disponible pour cette source."/><InfoCard title="VISITES / JOUR" value={fmt(data.derived?.visitsPerDay)} text="Moyenne depuis la création, calculée sur les visites cumulées."/><InfoCard title="FAVORIS / JOUR" value={fmt(data.derived?.favoritesPerDay)} text="Moyenne depuis la création."/><div className="panel wide"><div className="panelTitle"><div><span>CCU</span><h3>Historique observé</h3></div><span className="pill">Pas de faux historique</span></div>{gameHistory.length>1?<ResponsiveContainer width="100%" height={330}><LineChart data={gameHistory}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis/><Tooltip/><Line type="monotone" dataKey="playing" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer>:<EmptyChart text="Aucun historique public rétroactif disponible. Les observations commencent maintenant."/>}</div>{creatorSeries.length>1&&<div className="panel wide"><div className="panelTitle"><div><span>CREATOR ANALYTICS</span><h3>Daily Active Users</h3></div><span className="pill">Roblox · privé</span></div><ResponsiveContainer width="100%" height={330}><AreaChart data={creatorSeries}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" tickFormatter={v=>date(v)}/><YAxis/><Tooltip/><Area type="monotone" dataKey="value" fillOpacity={.12} strokeWidth={2}/></AreaChart></ResponsiveContainer></div>}</div>}
   {tab==='engagement'&&<div className="sectionGrid"><InfoCard title="PLAYERS / SERVEUR" value={data.derived?.playersPerServer?.toFixed(1)||'—'} text="CCU moyen théorique par rapport à la capacité configurée."/><InfoCard title="VISITE → FAVORI" value={pct(data.derived?.favoriteRate,3)} text="Proxy de conversion basé sur les compteurs publics."/><InfoCard title="CCU / VISITES" value={pct(data.derived?.concurrencyShare,5)} text="Rapport entre joueurs actuels et visites cumulées."/><InfoCard title="VISITES / JOUEUR ACTUEL" value={fmt(data.derived?.visitsPerPlaying)} text="Ratio de contexte, pas une durée de vie utilisateur."/><InfoCard title="VOTES" value={fmt((data.votes?.upVotes||0)+(data.votes?.downVotes||0))} text="Volume total de votes publics."/><InfoCard title="DISLIKES" value={fmt(data.votes?.downVotes)} text="Down-votes publics."/></div>}
   {tab==='growth'&&<div className="sectionGrid"><InfoCard title="VISITES / JOUR" value={fmt(data.derived?.visitsPerDay)} text="Visites cumulées divisées par l'âge du jeu."/><InfoCard title="FAVORIS / JOUR" value={fmt(data.derived?.favoritesPerDay)} text="Favoris cumulés divisés par l'âge du jeu."/><InfoCard title="ÂGE" value={days(data.derived?.ageDays)} text={`Créé le ${date(data.universe.created)}.`}/><InfoCard title="DERNIÈRE MAJ" value={date(data.universe.updated)} text="Dernière date de mise à jour exposée par Roblox."/><div className="panel wide"><div className="panelTitle"><div><span>MONÉTISATION</span><h3>Daily Revenue</h3></div><span className="pill">Creator Analytics requis</span></div>{revenueSeries.length>1?<ResponsiveContainer width="100%" height={300}><BarChart data={revenueSeries}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time" tickFormatter={v=>date(v)}/><YAxis/><Tooltip/><Bar dataKey="value"/></BarChart></ResponsiveContainer>:<EmptyChart text="Revenue historique masqué pour les jeux sans accès Creator Analytics."/>}</div></div>}
   {tab==='technical'&&<div className="sectionGrid"><InfoCard title="UNIVERSE ID" value={String(data.universe.id)} text="Identifiant stable de l'expérience."><button className="copy" onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copié':'Copier ID'}</button></InfoCard><InfoCard title="ROOT PLACE ID" value={String(data.universe.rootPlaceId)} text="Place principale de l'expérience."/><InfoCard title="MAX PLAYERS" value={fmt(data.universe.maxPlayers)} text="Capacité configurée par serveur."/><InfoCard title="CREATOR" value={data.creator?.displayName||data.universe.creator?.name||'—'} text={data.creator?.name?`@${data.creator.name}`:'Créateur Roblox'}/><InfoCard title="CRÉÉ" value={date(data.universe.created)} text={new Date(data.universe.created).toISOString()}/><InfoCard title="MIS À JOUR" value={date(data.universe.updated)} text={new Date(data.universe.updated).toISOString()}/><InfoCard title="PLACE" value={data.place?.name||'—'} text={data.place?.description||'Place details disponibles.'}/><InfoCard title="DONNÉES" value="PUBLIC" text="Les compteurs publics sont fournis par les endpoints Roblox."/><InfoCard title="ANALYTICS" value={data.history?.privateAnalytics?.enabled?'ACTIVE':'OFF'} text={data.history?.privateAnalytics?.enabled?'ROBLOX_API_KEY détectée.':'Ajoute ROBLOX_API_KEY pour les métriques propriétaires.'}/></div>}
   {tab==='raw'&&<pre className="raw">{JSON.stringify(data,null,2)}</pre>}
   <footer><span><Clock3 size={10}/> Fetched {new Date(data.fetchedAt).toLocaleTimeString('fr-FR')}</span><span><ShieldCheck size={10}/> Roblox public data · aucune métrique historique inventée</span></footer>
  </section>}
 </main>
}
