'use client'
import {useEffect,useMemo,useState} from 'react'
import {Search,Activity,Users,Eye,Heart,ThumbsUp,ThumbsDown,CalendarDays,RefreshCw,ExternalLink,Database,TrendingUp,Server,Gamepad2,Copy,Check,Info} from 'lucide-react'
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,BarChart,Bar} from 'recharts'

type Data=any
const fmt=(n:any)=>n==null?'—':Intl.NumberFormat('fr-FR',{notation:n>999999?'compact':'standard',maximumFractionDigits:1}).format(n)
const date=(s:any)=>s?new Date(s).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'}):'—'
function Metric({icon:Icon,label,value,sub,good}:{icon:any,label:string,value:any,sub?:string,good?:boolean}){return <div className="metric"><div className="metricIcon"><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong>{sub&&<small className={good?'up':''}>{sub}</small>}</div></div>}
function Spark({history}:{history:any[]}){return <div className="spark"><ResponsiveContainer width="100%" height="100%"><AreaChart data={history}><Area type="monotone" dataKey="playing" strokeWidth={2} fillOpacity={.12}/></AreaChart></ResponsiveContainer></div>}

export default function Home(){
 const [query,setQuery]=useState(''); const [data,setData]=useState<Data>(); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [tab,setTab]=useState('overview'); const [history,setHistory]=useState<any[]>([]); const [copied,setCopied]=useState(false)
 const load=async(q=query)=>{if(!q)return;setLoading(true);setError('');try{const r=await fetch('/api/roblox?q='+encodeURIComponent(q));const j=await r.json();if(!r.ok)throw Error(j.error);setData(j);setTab('overview')}catch(e:any){setError(e.message||'Impossible de récupérer les données')}finally{setLoading(false)}}
 useEffect(()=>{const raw=localStorage.getItem('rbx-history');if(raw)setHistory(JSON.parse(raw))},[])
 useEffect(()=>{if(!data)return;const point={time:Date.now(),label:new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),playing:data.universe.playing,visits:data.universe.visits};const next=[...history.filter(x=>x.id!==data.universe.id),{...point,id:data.universe.id}].slice(-60);setHistory(next);localStorage.setItem('rbx-history',JSON.stringify(next))},[data])
 const gameHistory=useMemo(()=>history.filter(x=>data&&x.id===data.universe.id),[history,data]);
 const copy=()=>{navigator.clipboard.writeText(String(data?.universe?.id));setCopied(true);setTimeout(()=>setCopied(false),1200)}
 return <main>
  <header className="top"><div className="brand"><div className="logo">R</div><div><b>RBX<span> Analytics</span></b><small>ROBLOX GAME INTELLIGENCE</small></div></div><div className="status"><i/> API CONNECTED</div></header>
  <section className="hero"><div className="eyebrow">ROBLOX DATA EXPLORER</div><h1>Analyse n'importe quel<br/><em>jeu Roblox.</em></h1><p>Des données publiques transformées en analytics avancées. Joueurs, visites, engagement, votes, serveurs et tendances.</p>
   <div className="search"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Nom du jeu, URL Roblox ou Universe ID…"/><button onClick={()=>load()} disabled={loading}>{loading?<RefreshCw className="spin" size={18}/>:<Search size={18}/>} Analyser</button></div>
   {error&&<div className="error">{error}</div>}
   <div className="examples"><span>Exemples :</span>{['Grow a Garden','Steal a Brainrot','Brookhaven RP','Blox Fruits'].map(x=><button key={x} onClick={()=>{setQuery(x);load(x)}}>{x}</button>)}</div>
  </section>
  {!data?<section className="empty"><Database size={34}/><h2>Ton laboratoire Roblox</h2><p>Recherche un jeu pour déverrouiller son profil analytique.</p><div className="features"><div><Activity/><b>Live metrics</b><small>Joueurs et signaux actuels</small></div><div><TrendingUp/><b>Derived analytics</b><small>Ratios et indicateurs calculés</small></div><div><Database/><b>History</b><small>Snapshots conservés localement</small></div></div></section>:
  <section className="dashboard">
   <div className="gameHead"><img src={data.media?.data?.[0]?.imageUrl||data.media?.data?.[0]?.url||''} onError={e=>(e.currentTarget.style.display='none')} /><div><div className="live"><i/> LIVE SNAPSHOT</div><h2>{data.universe.name}</h2><p>{data.universe.description||'Aucune description disponible.'}</p><div className="chips"><span>{data.universe.genre||'Unknown genre'}</span><span>Universe {data.universe.id}</span>{data.universe.isAllGenre?<span>All genre</span>:null}</div></div><a href={`https://www.roblox.com/games/${data.universe.rootPlaceId}`} target="_blank"><ExternalLink size={17}/> Roblox</a></div>
   <nav className="tabs">{[['overview','Overview'],['engagement','Engagement'],['votes','Votes & Rating'],['technical','Technical'],['raw','Raw Data']].map(([k,v])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{v}</button>)}<button className="refresh" onClick={()=>load()}><RefreshCw size={15}/></button></nav>
   {tab==='overview'&&<>
    <div className="metrics"><Metric icon={Users} label="PLAYING NOW" value={fmt(data.universe.playing)} sub="players online" good/><Metric icon={Eye} label="TOTAL VISITS" value={fmt(data.universe.visits)} sub={`${fmt(data.derived?.visitsPerLike)} visits / favorite`}/><Metric icon={Heart} label="FAVORITES" value={fmt(data.favorites)} sub="saved by players"/><Metric icon={ThumbsUp} label="LIKE RATE" value={data.derived?.likeRate!=null?data.derived.likeRate.toFixed(1)+'%':'—'} sub={`${fmt(data.votes?.upVotes)} likes`}/><Metric icon={Server} label="EST. SERVERS" value={fmt(data.derived?.estimatedServers)} sub={`${fmt(data.universe.maxPlayers)} max / server`}/><Metric icon={CalendarDays} label="UPDATED" value={date(data.universe.updated)} sub={`created ${date(data.universe.created)}`}/></div>
    <div className="grid2"><div className="panel"><div className="panelTitle"><div><span>CONCURRENT PLAYERS</span><h3>Live activity</h3></div><span className="pill">30s cache</span></div><div className="bigNumber">{fmt(data.universe.playing)} <small>players</small></div>{gameHistory.length>1?<Spark history={gameHistory}/>:<div className="chartEmpty">Les snapshots successifs apparaîtront ici.</div>}</div><div className="panel"><div className="panelTitle"><div><span>ENGAGEMENT SIGNALS</span><h3>Performance snapshot</h3></div></div><div className="bars"><div><label>Likes / dislikes</label><div className="bar"><i style={{width:`${Math.min(100,data.derived?.likeRate||0)}%`}}/></div><b>{data.derived?.likeRate?.toFixed(1)||'—'}%</b></div><div><label>Players / server capacity</label><div className="bar"><i style={{width:`${Math.min(100,(data.derived?.playersPerServer||0)/data.universe.maxPlayers*100)}%`}}/></div><b>{data.derived?.playersPerServer?.toFixed(1)||'—'}</b></div><div><label>Favorites / visits</label><div className="bar"><i style={{width:`${Math.min(100,(data.favorites/data.universe.visits||0)*1000)}%`}}/></div><b>{data.universe.visits?((data.favorites/data.universe.visits)*100).toFixed(3)+'%':'—'}</b></div></div></div></div>
   </>}
   {tab==='engagement'&&<div className="sectionGrid"><InfoCard title="PLAYER DENSITY" value={fmt(data.derived?.playersPerServer)} text="Estimated average concurrent players relative to the configured server capacity."/><InfoCard title="VISIT → FAVORITE" value={data.universe.visits?((data.favorites/data.universe.visits)*100).toFixed(3)+'%':'—'} text="Favorite conversion proxy. This is an analytical ratio, not an official Roblox metric."/><InfoCard title="CONCURRENCY / VISITS" value={data.derived?.visitToPlayer!=null?(data.derived.visitToPlayer*100).toFixed(5)+'%':'—'} text="A rough scale indicator comparing current concurrency to lifetime visits."/><InfoCard title="EST. ACTIVE SERVERS" value={fmt(data.derived?.estimatedServers)} text="Playing divided by maximum players per server, rounded up."/><div className="panel wide"><div className="panelTitle"><div><span>SNAPSHOT HISTORY</span><h3>Locally observed activity</h3></div></div>{gameHistory.length>1?<ResponsiveContainer width="100%" height={300}><AreaChart data={gameHistory}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis/><Tooltip/><Area type="monotone" dataKey="playing" fillOpacity={.15} strokeWidth={2}/></AreaChart></ResponsiveContainer>:<div className="chartEmpty">Reviens après quelques actualisations pour construire l'historique.</div>}</div></div>}
   {tab==='votes'&&<div className="sectionGrid"><InfoCard title="LIKES" value={fmt(data.votes?.upVotes)} text="Public up-vote count returned by Roblox."/><InfoCard title="DISLIKES" value={fmt(data.votes?.downVotes)} text="Public down-vote count returned by Roblox."/><InfoCard title="LIKE RATE" value={data.derived?.likeRate!=null?data.derived.likeRate.toFixed(2)+'%':'—'} text="Likes divided by total votes."/><InfoCard title="TOTAL VOTES" value={fmt((data.votes?.upVotes||0)+(data.votes?.downVotes||0))} text="Combined public vote volume."/></div>}
   {tab==='technical'&&<div className="sectionGrid"><InfoCard title="UNIVERSE ID" value={String(data.universe.id)} text=""><button className="copy" onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copied':'Copy ID'}</button></InfoCard><InfoCard title="ROOT PLACE ID" value={String(data.universe.rootPlaceId)} text="Main place associated with the experience."/><InfoCard title="MAX PLAYERS" value={fmt(data.universe.maxPlayers)} text="Configured maximum players per server."/><InfoCard title="CREATOR" value={data.creator?.displayName||data.universe.creator?.name||'—'} text={data.creator?.name?`@${data.creator.name}`:'Roblox creator'} /><InfoCard title="CREATED" value={date(data.universe.created)} text="Experience creation timestamp."/><InfoCard title="UPDATED" value={date(data.universe.updated)} text="Last known update timestamp."/></div>}
   {tab==='raw'&&<pre className="raw">{JSON.stringify(data,null,2)}</pre>}
   <footer><span>Data fetched {new Date(data.fetchedAt).toLocaleTimeString('fr-FR')}</span><span>Roblox public data • analytics calculated by RBX Analytics</span></footer>
  </section>}
 </main>
}
function InfoCard({title,value,text,children}:{title:string,value:any,text:string,children?:React.ReactNode}){return <div className="infoCard"><span>{title}</span><strong>{value}</strong><p>{text}</p>{children}</div>}
